# This is a basic workflow to help you get started with Actions

# Controls when the action will run. 
name: Blob storage website CI

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:            
    - uses: actions/checkout@v2
    - name: Build page
      run: npm run build
    - uses: azure/login@v1
      with:
          creds: ${{ secrets.STATIC_SITE2 }}
    - name: Upload to blob storage
      uses: azure/CLI@v1
      with:
 #       publish_dir: ./build
        azcliversion: 2.0.72
        inlineScript: |
            az storage blob upload-batch --account-name chtempstatic -d '$web' -s .

  # Azure logout 
    - name: logout
      run: |
            az logout
