# This is a basic workflow to help you get started with Actions

# Controls when the action will run. 
name: Blob storage website CI

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Packages
      run: npm install
    - name: Build page
      run: npm run build
    - name: Package app
      uses: actions/upload-artifact@v1
      with:
        name: reactApp
        path: ${{ env.OUTPUT_PATH }}

deployApp:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v1
        with:
          name: reactApp
          path: ${{ env.OUTPUT_PATH }}    

      - name: Upload to blob storage
      - uses: azure/login@v1
        with:
            creds: ${{ secrets.STATIC_SITE2 }}
      - uses: azure/CLI@v1
        with:
 #       publish_dir: ./build
          azcliversion: 2.0.72
          inlineScript: | 
            az storage blob upload-batch --account-name chtempstatic -d '$web' -s .

  # Azure logout 
    - name: logout
      run: |
            az logout
